### ISSUE TITLE
Missing git tags for 0.8.0 and 0.8.1

### ISSUE THREAD

**Issue by thomasdziedzic-census** [rockset/rockset-java-client#16]
https://mvnrepository.com/artifact/com.rockset/rockset-java lists 0.8.x but https://github.com/rockset/rockset-java-client/tags doesn't include them.

I would like to compare the changes between versions which is why I'm asking for the tags.

**Comment by ari-e** [comment]
Thanks for finding that @thomasdziedzic-census, I've added the necessary tags.

**Comment by thomasdziedzic-census** [comment]
Thanks!
