### ISSUE TITLE
RocksetDriver does not play nice with non `jdbc:rockset:` URLs

### ISSUE THREAD

**Issue by joelc** [rockset/rockset-java-client#47]
RocksetDriver defines `connect` thus:

```
if (!acceptsURL(url)) {
  log("Exit: Connect bad url" + url);
  throw new SQLException(
      "Bad url format " + url + ". Url should start with " + ROCKSET_DRIVER_URL_START + ".");
}
```

The JDBC contract specifies that implementations should return `null` if it's "the wrong kind of driver to connect to the given URL" (https://docs.oracle.com/javase/7/docs/api/java/sql/Driver.html#connect(java.lang.String,%20java.util.Properties).

The Rockset implementation _throws_ an exception.

This is breaking our application when there are multiple drivers registered. We have to work around by ensuring the Rockset driver is the last-registered class before we do anything in JDBC-space.

**Comment by joelc** [comment]
Strictly - this is not causing us issues. Apologies. The exception was a red herring, but probably shouldn't be thrown!

**Comment by notnoop** [comment]
Made a PR to be conformant to the JDBC specification. Thanks @joelc for pointing the issue out!
