### ISSUE TITLE
Inconsistent jackson dependency version

### ISSUE THREAD

**Issue by sap1ens** [rockset/rockset-java-client#60]
Currently, this project [uses different versions for different Jackson dependencies](https://github.com/rockset/rockset-java-client/blob/4c53e15d4341a2cb5b700d011f5d328aece616c0/pom.xml#L288-L297):

```xml
 <dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.13.2</version>
</dependency>
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.14.0</version>
</dependency>
```

which can lead to all kinds of issues downstream.

I think one Jackson version (2.14.0) should be used for all dependencies.

**Comment by sbaldwin-rs** [comment]
This has been fixed, thanks for bringing this to our attention and sorry for the delay!
